spring.application.name=expense-tracker-api

#MYSQL

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/expense-tracker
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

#JACKSON
spring.jackson.deserialization.fail-on-unknown-properties=false

